### ISSUE TITLE
Multiple multihash implementations

### ISSUE THREAD

**Issue by bmcorser** [ipfs/py-ipfs#13]
Just noticed there are (at least) two multihash implementations out there. Oddly, it appears as if they were created a few weeks apart:
- https://github.com/tehmaze/python-multihash
- https://github.com/bmcorser/py-multihash

@tehmaze's implementation is mentioned in the main ipfs documentation and actually does the hashing for the user, my implementation offers an interface and `__eq__`. Can they be merged under a common repo?

**Comment by moreati** [comment]
I apologize in advance for bike shedding, I'm going to suggest a 3rd option. Like @bmcorser I'd like to see a _single_, _canonical_ multihash package for Python, but I think it should expose an API based on stdlib's [hashlib](https://docs.python.org/3.5/library/hashlib.html). Ideally it would be usable as a drop in replacement.

I'll do a rough draft to flesh out the idea.

**Comment by BrendanBenshoof** [comment]
Just to exemplify this problem: https://github.com/BrendanBenshoof/py-multihash

I'm using it in UrDHT and just about any project that needs hashing.

**Comment by bmcorser** [comment]
@moreati :+1: for `hashlib` API

**Comment by JulienPalard** [comment]
Implemented an hashlib-compatible (PEP247) one, missing the "decode" part as the PEP obviously don't provide one. Also I'm not in the `decode` vocabulary, I think we can find better. And also I don't already know exactly why we would decode it :-p

BTW, here it is, just a draft, open for any merge in any directions to hopelessly avoid the https://xkcd.com/927/ effect.

https://github.com/JulienPalard/multihash

**Comment by BrendanBenshoof** [comment]
@jelien that looks great! we should add multiple hash value
encodings/decodings other than Hex. You also have some issues with not
using varInts, but that is long-term future proofing.

**Comment by JulienPalard** [comment]
Multiple hash values ? I'm not getting it, sry, what do you mean ?

varints ? I'm not sure I'm getting this one right, but, the spec for multihash is: `<1-byte hash function code><1-byte digest size in bytes>`, so what did I missed ?

**Comment by BrendanBenshoof** [comment]
multiple (hash value encodings) other than hex. Essentially other
bases/alphabets like base 64 or base 58. I'd write a general:
encode(bytes,alphabet)->string and decode(string,alphabet)->bytes then wrap
it with the default alphabets.

Read: https://github.com/jbenet/random-ideas/issues/1
especially the section on varints.

**Comment by JulienPalard** [comment]
I'm not sure it's the responsibility of the "hashlib" / "multihash-lib" to encode in base64.

Python already have a [https://docs.python.org/3.4/library/base64.html](base64) module to do this.

Also, doing the encoding in our hashlib-compatible implementation of multihash get our implementation away from PEP247. And by doing so, we cannot longer replace our multihash implementation by another (also PEP247 compliant) one.

I got it for varints, and will do, I open a ticket, yet we have plenty of time to do so, current implementation is compatible with varint up to 128 hashes :)

**Comment by JulienPalard** [comment]
Ticket opened about varint, I think I will NOT implement it until mandatory. The necessity will happen with a commit adding the 128th hash, that's a human intervention, not just the time flowing, so, adding this 128th will be the point in time we'll have to implement varint.

I mean, the cost of parsing a varint when we know for sure (list of known hashes is hardcoded) that we have less than a byte, is clearly a waste of time (human and CPU).

https://github.com/JulienPalard/multihash/issues/1

**Comment by BrendanBenshoof** [comment]
@julien +1 agreed/persuaded on all counts

**Comment by amstocker** [comment]
@JulienPalard I wrote a simple unsigned-varint conversion util for a [python multiaddr implementation](https://github.com/amstocker/python-multiaddr/blob/master/multiaddr/utils/varint.py) that I started.  You guys are definitely welcome to absorb or cherry pick from what I've started.

**Comment by JulienPalard** [comment]
@amstocker That's cool, thx, I'll probably put the code ready-to-use, like in a comment, but unused as long as it's not mandatory. As I said, it's not worth the cost of using varInt as long as the hardcoded list of supported hashes does not use the first byte.

**Comment by candeira** [comment]
I've made a plan for implementing multihash/multihashing [in this comment](https://github.com/ipfs/py-ipfs/issues/23#issuecomment-158345821). Feedback welcome.

**Comment by ntninja** [comment]
Reviewing the discussion here and on #23 I conclude that https://pypi.org/project/pymultihash/ is the one-stop go to solution for computing multihashes in python. I'll look into getting this moved into https://github.com/multiformats/py-multihash/ and added to the official list of implementations.

Closing this.
