### ISSUE TITLE
Development Hangout

### ISSUE THREAD

**Issue by BrendanBenshoof** [ipfs/py-ipfs#19]
I want to try and plan a developer hangout to start planning out the project and perhaps prepare for the first sprint.

We are a global "team" so scheduling is a mess.
I can commit to being available for any time chosen on this sat. or sun. with advanced notice.
If you are interested please post your availability for this weekend (make sure to mark timezone info or use utc)

**Comment by JulienPalard** [comment]
Interested but with family etc, can't give a precise hour. Also I'm in Paris, France, so Central European Time for me, probably won't match with a lot of you. Yet I think that following a precise roadmap may help focus our contributions and sync ourself, so I'll gladly pick from the sprint even if I can't join the hangout.

**Comment by amstocker** [comment]
I'm free this sunday

**Comment by BrendanBenshoof** [comment]
Looks like Sunday is our day then. @amstocker looks like we are it. When are you available?

**Comment by JulienPalard** [comment]
I'll probably be free sunday but don't know when, random will tell us ^^

**Comment by amstocker** [comment]
I'll be free mid afternoon PST.  Hopefully some others that have been active in the other thread will be able to join as well; @bmcorser @SilverWingedSeraph @mvanveen

**Comment by BrendanBenshoof** [comment]
I can do late EST: 8pm+ (PST 5pm+)

**Comment by amstocker** [comment]
@BrendanBenshoof That also works for me

**Comment by JulienPalard** [comment]
It's 2:00 AM Monday in CET, won't work for me :p but it's ok I'll backlog ^^

**Comment by BrendanBenshoof** [comment]
@whyrusleeping could you be in a hangout 5-6pm PST?

**Comment by BrendanBenshoof** [comment]
https://hangouts.google.com/call/23wp3q6mz2soebhv6ff4hjdjkea

^is a thing

**Comment by amstocker** [comment]
I'll be on in about 10 min
