### ISSUE TITLE
2 and 3

### ISSUE THREAD

**Issue by bmcorser** [ipfs/py-ipfs#2]
Despite this project not having any code written yet, we should support Python back to at least 2.7 to help with uptake of users who can't (or don't want to) work in a Python 3 environment.

Python 2.7 smoothes over many issues with `__future__`, but some guidance for developers would be useful.

Resources:
- [wiki](https://wiki.python.org/moin/Python2orPython3#Supporting_Python_2_and_Python_3_in_a_common_code_base) 3 stdlib in 2, general info
- [six](https://pythonhosted.org/six/) compatibility lib
- [a guide](http://python3porting.com/noconv.html) `print`, exceptions, imports, `L`, unicode
- [tox](https://tox.readthedocs.org/en/latest/) testing
- [setuptools](https://pythonhosted.org/setuptools/python3.html) packaging provision

**Comment by whyrusleeping** [comment]
from irc, I think that forward compatibility with 3 should be the goal, and not backwards compatibility with 2

**Comment by BrendanBenshoof** [comment]
I'm also going to second the "focus on python 3" approach. A year ago I would have agreed with you, but enough of the user base is catching up such that a python 2.7 version may not be merited. While the packages will be re-usable in other software the primary use case for the server modules will be to run an ipfs server, so I think it is reasonable to expect users to be able to install python3 to use it.

We made the python ipfs api 2.7 compatible because it's intent was to be integrated into other projects, where this software is intended to be standalone and talk to the reverse compatible api.

**Comment by sirMackk** [comment]
I would also opt for python 3. Lately I've encountered situations at work that made me wish we were using python 3 to get some of the basic goodies like unicode support and some of the more exotic ones like type hinting. I also believe that not focusing on python 2.7 will free up more time to work on the real issues.

**Comment by NoraCodes** [comment]
I agree with focusing on Python 3. The features it will enable are definitely worth it, in my opinion, and it is becoming much more prevalent - even Ubuntu will be shipping Python 3 as `/usr/bin/env python` soon.

**Comment by JulienPalard** [comment]
Python 3 is like 7 years old, I don't think "people who don't want to work in Python 3" should still be a thing. I vote for focusing exclusively on Python 3.

**Comment by NoraCodes** [comment]
Honestly, I would be happier to focus exclusively on Python3, as @JulienPalard suggests. It provides functionality which may be useful to the project, especially asyncio, and really should be the standard.

**Comment by mvanveen** [comment]
A _lot_ of the world is still on Python 2.  While it's true Python 3 is "like 7 years old," it still makes up a fraction of the current Python install base and mind share.  To provide my own anecdotal evidence, I've been a Python dev for about 10 years now, having the breadth of my professional experiences centered almost exclusively within the lang, and I have yet to have had the luxury of working on a python 3 project in those settings thus far.

I want to see Python 3 adoption as much as anyone, and there's a lot of great features of Python 3 that I think we'd probably want to leverage.  I bet the new event loop architecture is going to really come in handy later, and there might be specific advantages to Python 3 that outweigh compatibility.

But I think for a reference implementation pragmatism should beat out idealism.  If we want to see wider ipfs adoption we should have a lib that works for the common man, and the common man has Python 2.7 installed by default.  As such, I'd favor supporting both 2 and 3.

There are also a lot of ways we can still take advantage of Python 3 features by using Python 2 backported implementations (e.g. `enum34`, `unittest2`, etc.).

This seems like an unpopular pov currently and I hate to be the uncooperative voice of dissent.  So in the name of consensus I'm personally going to stick developing with Python 3-only requirment until other people chime in.

Nevertheless, I'd like to request that we examine this issue carefully.

I think there's a lot of merit to striving for both 2 and 3 compliance as far as increasing adoption, so I don't think dropping Python 2 support is a decision we should make lightly.  From a sort of product perspective I think it will greatly impact how relevant our codebase is to the greater Python community.

**Comment by bmcorser** [comment]
I feel the spirit of my issue is slipping away ...

> we should support Python back to at least 2.7

The implication here is that we _should_ focus on developing against Python 3, but we _should also_ maintain compatibility back to 2.7 ... 

In my opinion not supporting Python 2.7 at all isn't an option if this project wants to be used by the world at large. As @mvanveen mentioned, the world at large (in my experience too) are still teetering at the edge of Python 2.7 (ie 2.7.**10** lol). Here's [a PDF](https://wiki.python.org/moin/2.x-vs-3.x-survey?action=AttachFile&do=get&target=2013-2014+Python+2.x-3.x+survey.pdf) showing some 2/3 usage stats from last year.

If this issue is going to hold people up from starting to contribute to this project, we should probably just have a vote and be done with it ...

**Comment by bmcorser** [comment]
:point_up: #18

**Comment by bmcorser** [comment]
Closing this.

By democratic process; we shall not be supporting Python 2.

**Comment by jbenet** [comment]
I think Michael is right, if this implementation hopes to see strong, wide use, it should support python 2.7. The world really hasn't moved forward on this.

As an anecdotal single data point, in all my years developing Python distributed systems I've yet to _ever_ run Python 3.

I don't think the sample size of this issue is large enough to determine an accurate distribution of use. We should look at graphs of real deployments. 

—
