### ISSUE TITLE
Alternative Interchanging Format

### ISSUE THREAD

**Issue by Mec-iS** [ipfs/py-ipfs#25]
As there is no official Protocol Buffers working support yet for Python3, it would be great if server and client could support https://capnproto.org/

**Comment by NoraCodes** [comment]
Correct me if I misunderstood, but it seems that this would totally break interoperability with other IPFS nodes.

**Comment by jbenet** [comment]
Yes it would. you need protobuf for interop with other ipfs nodes today.

**Comment by NoraCodes** [comment]
The best solution would be to either make the interchange pluggable or allocate some of this group's development effort toward fixing Python3 protobuf.

**Comment by Mec-iS** [comment]
there is something working here: https://github.com/GreatFruitOmsk/protobuf-py3 but no news about official support yet. 
@jgraef told me on chat he coded a simple encoder-decoder for Py3.

**Comment by NoraCodes** [comment]
If it's functional and has the same or a similar interface to the official protobuf solution, we should use that and retrofit with the official package when it becomes available. Efficiency of the code is secondary to our ability to begin development.

**Comment by jbenet** [comment]
AFAIK there are multiple unofficial implementations that work.

**Comment by jgraef** [comment]
https://github.com/jgraef/python3-ipfs-api/tree/master/ipfs/pb2hack

There is also a proto package which includes protocols for PBNode and unixfs. Protocols are specified with python objects (no protobuf specification parser yet) and are interpreted while reading/writing.

It only supports the data types that are used in PBNode and unixfs (string, bytes, uint*)

This module is called "hack" for a reason. I don't recommend using it for a larger project like py-ipfs.

**Comment by Mec-iS** [comment]
If I understood well, we are going to start with py-libp2p.
I started taking some notes [here](https://github.com/ipfs/specs/issues/68)
