### ISSUE TITLE
How do I begin working on py-ipfs?

### ISSUE THREAD

**Issue by ghost** [ipfs/py-ipfs#33]
I am interested in contributing to Python implementation of IPFS but I don't know where to begin. I initially had an idea of doing this via basing it on JS variant but every library I look at -- libp2p or peer-id or ipld they all have internal dependencies to each other and other libraries like multihashing or libp2p.

So I am right now stuck on where to begin contribution. I understood libp2p is important and so I peeked at js variant. It's dependent on so many libraries which are in-turn dependent on other libraries.

What to do? Can anyone please help? AS a beginner to this, I'd like some guidance please!

**Comment by RichardLitt** [comment]
Great question, @shanmukhateja! Changed the title a bit and added labels to help make this easier to answer.

**Comment by daviddias** [comment]
Hey @shanmukhateja, the best way to start is by implementing the supporting modules: https://github.com/ipfs/community/issues/177, let me know if this helps to get you started :)

**Comment by ghost** [comment]
Hey thank you for reaching out @RichardLitt  @diasdavid . I was a bit worried that I'd be frowned upon for this issue. 

@diasdavid  Thank you for the link. I have been catching up on what to do and I'll post anything I find.

**Comment by RichardLitt** [comment]
No, no, that's a great question. We're happy to help. (Anything that made it seem you like you'd be frowned upon?) 

Do post any other questions if you've got em. :)

**Comment by ghost** [comment]
NO I haven't seen anything of that sort but it's just that the issues page was filled with technical queries related to IPFS implementation or dev meetings and ROADMAPs. SO I was a little worried.

**Comment by RichardLitt** [comment]
OK. We'll try to make it more accessible if we can, thanks for the feedback!

**Comment by mhchia** [comment]
Hi all,
Thank you in advance for reading my comment.

I just learned ipfs recently, and I am really interested in the project.
And I found py-ipfs, which is marked as welcoming contribution.

As @diasdavid said,
> the best way to start is by implementing the supporting modules: ipfs/community#177

I checked the supporting modules in ipfs/community#177, and they seemed not implemented yet in py-ipfs.
So I wonder if py-ipfs still welcomes contribution from a newbie like me, and if the answer is yes then which part should be implemented first?

**Comment by ankagrawal** [comment]
Hi.. looks like py-ipfs is dormant since quite sometime. Has the project moved somewhere else?

I am wondering if the roadmap present on https://github.com/ipfs/py-ipfs and list of existing issues is still current. Also the link https://github.com/ipfs/py-ipfs/issues/1%7D seems to be not working anymore. Can someone please help me with the list of current issues.
I am interesting in contributing to this project, and it would be great to get some pointers about that.

**Comment by shenghuatang** [comment]
Is this project stopped?

**Comment by ntninja** [comment]
@shenghuatang: As far as I know it never really started, but if you're interested in helping please see my response to vuonghv in [this comment](https://github.com/ipfs/py-ipfs/issues/1#issuecomment-353691198) on the other thread. Feel free to leave a comment if you want to know more.

**Comment by ntninja** [comment]
Issue #49 has details on what we could currently use help in. Closing this issue in favour of that one.
