### ISSUE TITLE
Get file module saves the file with the hash as the filename

### ISSUE THREAD

**Issue by shshnkvadali** [ipfs/py-ipfs#43]
With the following code 
`api = ipfsapi.connect('127.0.0.1', 5001)`
`api.get(<hash>)`
The file is downloaded and is renamed as hash. I'm not certain if this is done on purpose or an issue that needs to be resolved

**Comment by ntninja** [comment]
Sorry for the lack of response, but you commented in the wrong repo at the wrong time unfortunately. If your still interested in discussing this please open an issue at https://github.com/ipfs/py-ipfs-api instead.
