### ISSUE TITLE
i want to join to dev python-ipfs.

### ISSUE THREAD

**Issue by threadshare** [ipfs/py-ipfs#46]
i want to join to dev python-ipfs. i saw this project starting. i am a python developer. i work for eos blockchain. i am interested in blockchain and ipfs. i used python,golang,php. ipfs is cool. so i want to join it and dev a new internet.
so how can i join python-ipfs. first maybe i can pr, but there are maybe other developer build it. so i create this issue. i hope to join them,but i don’t how to do that.
and sorry to create this issue just to do for that. but i’m really interested in ipfs.

if you have free time, please give a replay. and if i can’t join it,please give me some advice to tell me how to contribute.

my email: zhichaozhang3@gmail.com

thanks,
goooo

**Comment by ntninja** [comment]
@GiggleAll: I just mentioned you in #1, please see my response there. I'm happy to provide some guidance on things but there is currently no existing “team” you could join unfortunately. Also the current contents of this repo are just a bunch of empty stubs and can be totally ignored for any feature py-IPFS developments.
