### ISSUE TITLE
Pull request review process

### ISSUE THREAD

**Issue by ngetahun** [ipfs/py-ipfs#47]
There are 4 open PRs from a year ago, and it would be nice if we could delegate someone to do the reviews

**Comment by ntninja** [comment]
At the time when those PRs where opened there were unfortunately no active caretakers assigned to this project – meaning that there are still no active developers. (I only ended up by a kind of accident in this role later that year and only noticed those PRs today thanks to you. :slightly_smiling_face:)
See the recent comments on #1 for the current status of this: There is nothing usable here and there is no particular reason to retain anything from this repo aside from maybe a few scraps of documentation.
