### ISSUE TITLE
Some question regarding Py-IPFS

### ISSUE THREAD

**Issue by DonaldTsang** [ipfs/py-ipfs#48]
1. Does it have the no-copy bug like go-ipfs, where the pinned file will be duplicated in the disk?
    - https://github.com/ipfs/go-ipfs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+nocopy
2. Does Py-IPFS has hashes algorithms for SHA256, BLAKE2b, BLAKE2s and Skein?
    - For reference SHA256 and BLAKE2 are in the standard library, and Skein is in https://pythonhosted.org/pyskein/

**Comment by ntninja** [comment]
Sorry, but py-ipfs does none of these things currently as there isn't really any code yet. See #1 for the current status.

**Comment by DonaldTsang** [comment]
@alexander255 please read this https://github.com/ipfs/go-ipfs/issues/4558
Does Py-IPFS has the same problem as Go-IPFS?

**Comment by ntninja** [comment]
@DonaldTsang: Py-IPFS isn't a usable product yet and, among many other things, does not have storage support (and therefor `add` yet). So no, technically it is not affected but that still won't help you. :wink:
